"use client";

import { useQuery } from "@tanstack/react-query";
import type { EChartsOption } from "echarts";
import { useMemo } from "react";
import { EChart } from "@/components/charts/echart";
import { StatusBadge } from "@/components/ui/status-badge";
import { queries } from "@/lib/api/queries";
import { label, number, utc } from "@/lib/format";

const pipeline = ["Feedback", "Validation", "Dataset", "Training", "Candidate", "Challenger", "Governance", "Promotion"];

export function LearningClient() {
  const drift = useQuery({ queryKey: ["drift"], queryFn: queries.drift, refetchInterval: 30_000 });
  const feedback = useQuery({ queryKey: ["feedback"], queryFn: queries.feedback, refetchInterval: 30_000 });
  const models = useQuery({ queryKey: ["models"], queryFn: queries.models });
  const chart = useMemo<EChartsOption>(() => ({ backgroundColor: "transparent", tooltip: { trigger: "axis", backgroundColor: "var(--surface-elevated)", borderColor: "var(--border-strong)", textStyle: { color: "var(--text-primary)" } }, grid: { left: 38, right: 12, top: 16, bottom: 28 }, xAxis: { type: "category", data: drift.data?.events.map((item) => utc(item.timestamp, true).replace(" UTC", "")) ?? [], axisLabel: { color: "var(--text-muted)", fontSize: 9 } }, yAxis: { type: "value", axisLabel: { color: "var(--text-muted)", fontSize: 9 }, splitLine: { lineStyle: { color: "var(--border-subtle)" } } }, series: [{ type: "line", data: drift.data?.events.map((item) => item.score) ?? [], showSymbol: true, lineStyle: { color: "var(--accent)" }, itemStyle: { color: "var(--accent)" } }, { type: "line", data: drift.data?.events.map((item) => item.threshold) ?? [], showSymbol: false, lineStyle: { color: "var(--warning)", type: "dashed" } }] }), [drift.data]);
  const datasets = [...new Set(Object.values(models.data?.registry ?? {}).flatMap((entry) => [entry.champion?.dataset_id, entry.challenger?.dataset_id]).filter(Boolean))];
  return <div><header className="page-heading"><div><h2>Continuous learning</h2><p>Signals and analyst judgements remain offline candidates until explicit governance approval.</p></div><StatusBadge value="READY" /></header><section className="learning-pipeline" aria-label="Continuous learning stages">{pipeline.map((stage, index) => <div key={stage}><i>{index + 1}</i><span>{stage}</span>{index < pipeline.length - 1 ? <b /> : null}</div>)}</section><section className="learning-grid"><div className="surface learning-chart"><div className="section-heading"><div><span className="eyebrow">Model drift</span><h3>Score against threshold</h3></div><span>{drift.data?.count ?? 0} signals</span></div>{drift.data?.events.length ? <EChart option={chart} className="drift-chart" /> : <div className="compact-empty">No drift events recorded.</div>}</div><div className="surface feedback-summary"><div className="section-heading"><div><span className="eyebrow">Feedback queue</span><h3>Training candidates</h3></div><strong className="mono">{feedback.data?.count ?? 0}</strong></div><p>Analyst feedback is stored for reviewed dataset construction. It cannot alter a production model.</p><dl><div><dt>Unconsumed judgements</dt><dd>{feedback.data?.feedback.filter((item) => !item.consumed_by_dataset).length ?? 0}</dd></div><div><dt>Referenced datasets</dt><dd>{datasets.length}</dd></div></dl></div></section><section className="surface data-region drift-table"><table className="data-table"><thead><tr><th>Time</th><th>Detector</th><th>Feature</th><th>Metric</th><th className="numeric">Score</th><th className="numeric">Threshold</th><th>Status</th><th>Recommendation</th></tr></thead><tbody>{drift.data?.events.map((item) => <tr key={item.drift_id}><td className="mono">{utc(item.timestamp, true)}</td><td>{label(item.detector)}</td><td className="mono">{item.feature ?? "—"}</td><td>{label(item.metric)}</td><td className="numeric">{number(item.score, 3)}</td><td className="numeric">{number(item.threshold, 3)}</td><td><StatusBadge value={item.score >= item.threshold ? "DEGRADED" : "READY"} /></td><td>{item.recommendation}</td></tr>)}{!drift.data?.events.length ? <tr><td colSpan={8} className="empty-row"><strong>No drift events recorded.</strong></td></tr> : null}</tbody></table></section></div>;
}
